{{ if .Values.gcePersistentDiskName }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.gcePersistentDiskName }}-gcepd
spec:
  storageClassName: ""
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ .Values.gcePersistentDiskName | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.gcePersistentDiskName }}-gcepd
spec:
  storageClassName: ""
  volumeName: {{ .Release.Namespace }}-{{ .Values.gcePersistentDiskName }}-gcepd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
{{ end }}
