{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: {{ .Values.image | default "budgetkey/open-budget-elasticsearch:latest" | quote }}
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: {{ .Values.resources }}
        env:
        - name: ES_JAVA_OPTS
          # -Dlog4j2.formatMsgNoLookups=true is required to mitigate CVE-2021-44228
          value: {{ printf "-Dlog4j2.formatMsgNoLookups=true %s" .Values.ES_JAVA_OPTS | quote }}
        - name: xpack.security.enabled
          value: "false"
        - name: discovery.type
          value: single-node
        - name: DECODE_KEY
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: DECODE_KEY}}
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elasticsearch2
      # {{ if .Values.gcePersistentDiskName }}
      #   persistentVolumeClaim:
      #     claimName: {{ .Release.Namespace }}-{{ .Values.gcePersistentDiskName }}-gcepd
      # {{ else if .Values.nfsServer }}
      #   nfs:
      #     server: {{ .Values.nfsServer | quote }}
      #     path: {{ .Values.nfsPath | quote }}
      # {{ else }}
      #   {{ .Values.global.persistentDataVolume.type }}: {
      #     {{ if eq .Values.global.persistentDataVolume.type "hostPath" }}
      #     "path": "{{ .Values.global.persistentDataVolume.basePath }}/elasticsearch",
      #     "type": "DirectoryOrCreate"
      #     {{ end }}
      #   }
      # {{ end }}
{{ end }}
