data-api:
  image: budgetkey/open-budget-data-api:584f2ea5fa3bc3220287be0a97f6bc5482e8ba0c
elasticsearch:
  image: budgetkey/open-budget-elasticsearch-commercial:latest
internal-search-ui:
  backendImage: uumpa/hasadna-nli-z3950:990d2bae23efe40bc6ae2029cb4c4dc75e52c85c
  image: uumpa/hasadna-migdar-internal-search-ui:a015ccee84d3e47d086c61aaccdc508c4570b908
nginx:
  image: budgetkey/open-budget-nginx-frontend:d8cbc9e27c438584170ee5ab3bc1896e1727f0d1
pipelines:
  image: hasadna/migdar-data-pipelines:2a682f08f51669f7ce642d9ee4639503cc86e039
postgres:
  image: budgetkey/budgetkey-postgres:3efcf352910056cd965ca9a0212722fa03fb1840
search-api:
  image: hasadna/migdar-search-api:90c2ab83fc601fd090ce0fbca9b34e9b2382a26a
