app-generic-item:
  enabled: false
  resources: >
    {"requests": {"cpu": "30m", "memory": "100Mi"}, "limits": {"memory": "300Mi"}}

app-main-page:
  enabled: false
  resources: >
    {"requests": {"cpu": "30m", "memory": "100Mi"}, "limits": {"memory": "300Mi"}}

app-profile:
  enabled: false
  resources: >
    {"requests": {"cpu": "30m", "memory": "100Mi"}, "limits": {"memory": "300Mi"}}

app-about:
  enabled: false
  resources: >
    {"requests": {"cpu": "30m", "memory": "100Mi"}, "limits": {"memory": "300Mi"}}

app-search:
  enabled: false
  resources: >
    {"requests": {"cpu": "30m", "memory": "100Mi"}, "limits": {"memory": "300Mi"}}

emails:
  enabled: false
  resources: >
    {"requests": {"cpu": "30m", "memory": "100Mi"}, "limits": {"memory": "1Gi"}}

auth:
  enabled: false
  resources: >
    {"requests": {"cpu": "40m", "memory": "100Mi"}, "limits": {"memory": "300Mi"}}

data-api:
  enabled: false
  resources: >
    {"requests": {"cpu": "45m", "memory": "50Mi"}, "limits": {"memory": "300Mi"}}

db-backup:
  enabled: false
  resources: >
    {"requests": {"cpu": "10m", "memory": "100Mi"}, "limits": {"cpu": "50m", "memory": "200Mi"}}

elasticsearch:
  enabled: false
  resources: >
    {"requests": {"cpu": "100m", "memory": "250Mi"}, "limits": {"memory": "500Mi"}}
  ES_JAVA_OPTS: "-Xms250m -Xmx250m"

kibana:
  enabled: false
  resources: >
    {"requests": {"cpu": "25m", "memory": "335Mi"}, "limits": {"cpu": "102m", "memory": "1492Mi"}}

list-manager:
  enabled: false
  resources: >
    {"requests": {"cpu": "40m", "memory": "100Mi"}, "limits": {"memory": "300Mi"}}

nginx:
  enabled: false
  resources: >
    {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "48m", "memory": "256Mi"}}

pipelines:
  enabled: false
  resources: >
    {"requests": {"cpu": "35m", "memory": "776Mi"}, "limits": {"cpu": "218m", "memory": "3456Mi"}}

postgres:
  enabled: false
  resources: >
    {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "48m", "memory": "256Mi"}}

search-api:
  enabled: false
  resources: >
    {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "48m", "memory": "270Mi"}}

socialmap:
  enabled: false
  mainpageResources: >
    {"requests": {"cpu": "30m", "memory": "100Mi"}, "limits": {"memory": "300Mi"}}

openprocure:
  enabled: false
  mainpageResources: >
    {"requests": {"cpu": "30m", "memory": "100Mi"}, "limits": {"memory": "300Mi"}}

themes:
  enabled: false
  resources: >
    {"requests": {"cpu": "1m", "memory": "10Mi"}, "limits": {"memory": "200Mi"}}
