{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: search-api
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: search-api
        image: {{ .Values.image | default "hasadna/migdar-search-api:latest" | quote }}
        ports:
        - containerPort: 8000
        resources: {{ .Values.resources }}
        env:
        - name: ES_HOST
          value: elasticsearch
        - name: ES_PORT
          value: "9200"
        - name: INDEX_NAME
          value: {{ .Values.INDEX_NAME | default "migdar" | quote }}
{{ end }}
