{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default_server.conf: |
    server_name  yodaat.org www.yodaat.org;

  api_server.conf: |
    server_name  api.yodaat.org;

  kibana.conf: |
    server {
        listen 80;
        server_name  kibana.migdar.org;
        client_max_body_size 50m;
        location / {
            proxy_pass http://kibana:5601;
            auth_basic "Kibana";
            auth_basic_user_file /etc/nginx/kibana.htpasswd;
        }
    }

  kibana.htpasswd: |
    migdar:$apr1$osnd5bKS$QCBIR1f6GiqNpN3b/hqzP.

  server-rules.conf: |
    location /pipelines/ {
        proxy_pass http://pipelines:5000/;
    }
  
    location /datapackages {
       proxy_pass http://pipelines;
    }

    location / {
        proxy_pass http://web-ui:8000/;
    }

  api-server-rules.conf: |
    location /search/ {
        proxy_pass http://search-api:8000;
    }

    location /get/ {
        proxy_pass http://search-api:8000;
    }

    # location /api/ {
    #     proxy_pass http://data-api:8000;
    # }

  servers.conf: |
    server {
        listen 80;
        include /etc/nginx/api_server.conf;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        include "/etc/nginx/api-server-rules.conf";
    }

    server {
        listen 80 default_server;
        include /etc/nginx/default_server.conf;
        error_page 500 502 503 504 /500.html;
        location = /500.html {
            root /usr/share/nginx/errors;
            internal;
        }
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        include "/etc/nginx/server-rules.conf";
    }

{{ end }}
