{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default_server.conf: |
    server_name  yodaat.org;

  servers.conf: |
#    server {
#      server_name data.obudget.org;
#      return 301 https://app.redash.io/hasadna/;
#    }

#    server {
#      server_name obudget.org www.obudget.org;
#      rewrite ^ https://next.obudget.org/ permanent;
#    }

#    server {
#      server_name socialmap.org.il www.socialmap.org.il;
#      location / {
#        proxy_pass http://socialmap-app-main-page:8000/;
#      }
#    }

  kibana.conf: |
    server {
        listen 80;
        server_name  kibana.migdar.org;
        client_max_body_size 50m;
        location / {
            proxy_pass http://kibana:5601;
            auth_basic "Kibana";
            auth_basic_user_file /etc/nginx/kibana.htpasswd;
        }
    }

  kibana.htpasswd: |
    migdar:$apr1$osnd5bKS$QCBIR1f6GiqNpN3b/hqzP.

  server-rules.conf: |
    # location /search/ {
    #     proxy_pass http://search-api:8000;
    # }

    # location /get/ {
    #     proxy_pass http://search-api:8000;
    # }

    # location /api/ {
    #     proxy_pass http://data-api:8000;
    # }

    location /pipelines/ {
        proxy_pass http://pipelines:5000/;
    }

    location /datapackages {
       proxy_pass http://pipelines;
    }

    location / {
        proxy_pass http://web-ui:8000/;
    }
{{ end }}
