{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  {{ if .Values.enableAntiAffinity }}
  affinity:
    # ensure nginx won't be on the same node as elasticsearch
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - elasticsearch
        topologyKey: "kubernetes.io/hostname"
  {{ end }}
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        # this is plain nginx alpine with embedded fonts
        # all nginx configurations are done using the configmap
        image: hasadna/migdar-nginx@sha256:9b14390c21bcac5a1fcd1159ba8fa7a980e2e5fba08c49fbe2def2c4e9527397
        ports:
        - containerPort: 80
        resources: {{ .Values.resources }}
        volumeMounts:
        - name: configmap
          mountPath: /etc/nginx/servers.conf
          subPath: servers.conf
        - name: configmap
          mountPath: /etc/nginx/default_server.conf
          subPath: default_server.conf
        - name: configmap
          mountPath: /etc/nginx/api_server.conf
          subPath: api_server.conf
        - name: configmap
          mountPath: /etc/nginx/conf.d/kibana.conf
          subPath: kibana.conf
        - name: configmap
          mountPath: /etc/nginx/kibana.htpasswd
          subPath: kibana.htpasswd
        - name: configmap
          mountPath: /etc/nginx/server-rules.conf
          subPath: server-rules.conf
        - name: configmap
          mountPath: /etc/nginx/api-server-rules.conf
          subPath: api-server-rules.conf
      volumes:
      - name: configmap
        configMap:
          name: nginx
{{ end }}
