{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelines-nginx-conf
data:
  default.conf: |
    server {
      listen 80 default_server;
      location /data {
        root /pipelines/;
        autoindex on;
      }
    }
{{ end }}
