apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: deployment-pipelines
spec:
  targetRef:
    apiVersion: apps/v1
    kind: deployment
    name: pipelines
  updatePolicy:
    updateMode: "Off"
