apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: '80'
    port: 80
  selector:
    app: nginx
  {{ if .Values.enableLoadBalancer }}
  type: LoadBalancer
  {{ if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP | quote }}
  {{ end }}
  {{ end }}
