{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: data-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: data-api
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: data-api
        image: {{ .Values.image | default "budgetkey/open-budget-data-api:latest" | quote }}
        ports:
        - containerPort: 8000
        resources: {{ .Values.resources }}
        env:
        - name: SERVER_NAME
          value: {{ .Values.global.serverName | default "migdar.org" | quote }}
        {{ if .Values.secretName }}
        - name: DATABASE_URL
          valueFrom: {secretKeyRef: {name: {{ .Values.secretName | quote }}, key: DATABASE_URL}}
        {{ else }}
        - name: DATABASE_URL
          value: postgresql://migdar:123456@postgres/migdar
        {{ end }}
{{ end }}
