apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: deployment-postgres
spec:
  targetRef:
    apiVersion: apps/v1
    kind: deployment
    name: postgres
  updatePolicy:
    updateMode: "Off"
