{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: {{ .Values.image | default "elastic/kibana:7.3.2" | quote }}
        ports:
        - containerPort: 5601
        resources: {{ .Values.resources }}
{{ end }}
